name: deploy

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      HOST_IP: ${{ secrets.HOST_IP }}
      HOST_USER: ${{ vars.HOST_USER }}
      SUBDOMAIN: ${{ vars.SUBDOMAIN }}
      DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
      TIMEZONE: ${{ vars.TIMEZONE }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      N8N_PORT: ${{ vars.N8N_PORT }}
      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.0
          bundler-cache: true

      - name: Install Kamal
        run: gem install kamal

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        env:
          N8N_PORT: ${{ env.N8N_PORT }}
    
      - name: Use Kamal to deploy n8n
        run: |
          if ! kamal accessory logs db 2>/dev/null; then
            kamal setup
          else
            kamal deploy
          fi